# Generated by Django 5.2.5 on 2025-09-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('street_number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('pickup_deadline', models.DateTimeField()),
                ('pickup_type', models.CharField(choices=[('Retirada no local', 'Retirada no local'), ('Entrega', 'Entrega')], max_length=50)),
                ('reservation_status', models.CharField(choices=[('Available', 'Disponível'), ('Reserved', 'Reservado'), ('Collected', 'Coletado'), ('Expired', 'Expirado'), ('Cancelled', 'Cancelado')], default='Available', max_length=20)),
                ('redemption_point', models.IntegerField()),
                ('item_quantity', models.IntegerField()),
                ('max_pickup', models.IntegerField()),
                ('url_image', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('legal_name', models.CharField(max_length=100)),
                ('trade_name', models.CharField(max_length=100)),
                ('url_image', models.URLField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.address')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('initial_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.item')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1)),
                ('education_level', models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Ensino Superior', 'Ensino Superior'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], default='Ensino Médio', max_length=50)),
                ('marital_status', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a)', 'Separado(a)')], default='Solteiro(a)', max_length=20)),
                ('total_income', models.IntegerField()),
                ('current_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managament.address')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managament.company')),
            ],
        ),
        migrations.CreateModel(
            name='Redemption_point',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.company')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Transaction',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('pickup_time', models.DateTimeField()),
        #         ('pickup_quantity', models.IntegerField()),
        #         ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.person')),
        #         ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.item')),
        #     ],
        # ),
    ]
