# Generated by Django 5.2.4 on 2025-07-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Person',
        ),
    ]
