# Generated by Django 5.2.4 on 2025-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_rename_data_nascimento_person_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
