# Generated by Django 5.2.4 on 2025-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='address_id',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
