# Generated by Django 5.2.4 on 2025-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_remove_person_address_person_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='total_income',
            field=models.IntegerField(),
        ),
    ]
