# Generated by Django 5.2.4 on 2025-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_person_address_id_alter_person_total_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.TextField(max_length=100)),
                ('street', models.TextField(max_length=255)),
                ('neighborhood', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=50)),
                ('street_number', models.IntegerField(max_length=20)),
                ('complement', models.TextField(max_length=20)),
            ],
        ),
    ]
