# Generated by Django 5.2.4 on 2025-07-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.TextField(max_length=14)),
                ('address_id', models.IntegerField()),
                ('legal_name', models.TextField(max_length=100)),
                ('trade_name', models.TextField(max_length=100)),
                ('url_image', models.TextField(max_length=255)),
            ],
        ),
    ]
