# Generated by Django 5.2.4 on 2025-07-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_remove_company_address_id_remove_person_address_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('pickup_deadline', models.DateTimeField()),
                ('pickup_type', models.CharField(choices=[('Retirada no local', 'Retirada no local'), ('Entrega', 'Entrega')], max_length=50)),
                ('reservation_status', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservado', 'Reservado'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=20)),
                ('redemption_point', models.IntegerField()),
                ('item_quantity', models.IntegerField()),
                ('max_pickup', models.IntegerField()),
                ('url_image', models.TextField(max_length=255)),
            ],
        ),
    ]
