# Generated by Django 5.2.4 on 2025-07-29 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reservation_status',
            field=models.CharField(choices=[('Availçable', 'Disponível'), ('Reserved', 'Reservado'), ('Collected', 'coletado'), ('Expired', 'Expirado'), ('Cancelled', 'Cancelado')], default='Disponível', max_length=20),
        ),
        migrations.CreateModel(
            name='Trasaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField()),
                ('pickup_quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.item')),
            ],
        ),
    ]
