# Generated by Django 5.2.4 on 2025-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_alter_item_reservation_status_trasaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasaction',
            new_name='Transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='person_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='item_id',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='item',
            name='reservation_status',
            field=models.CharField(choices=[('Available', 'Disponível'), ('Reserved', 'Reservado'), ('Collected', 'Coletado'), ('Expired', 'Expirado'), ('Cancelled', 'Cancelado')], default='Available', max_length=20),
        ),
    ]
