# Generated by Django 5.2.4 on 2025-07-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_rename_trasaction_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='person',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='item',
            new_name='person_id',
        ),
        migrations.CreateModel(
            name='Redemption_point',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.company')),
            ],
        ),
    ]
