# Generated by Django 5.2.5 on 2025-09-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('street_number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('pickup_deadline', models.DateTimeField()),
                ('pickup_type', models.CharField(choices=[('Retirada no local', 'Retirada no local'), ('Entrega', 'Entrega')], max_length=50)),
                ('reservation_status', models.CharField(choices=[('Available', 'Disponível'), ('Reserved', 'Reservado'), ('Collected', 'Coletado'), ('Expired', 'Expirado'), ('Cancelled', 'Cancelado')], default='Available', max_length=30)),
                ('item_quantity', models.IntegerField()),
                ('max_pickup', models.IntegerField()),
                ('url_image', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('legal_name', models.CharField(max_length=100)),
                ('trade_name', models.CharField(max_length=100)),
                ('url_image', models.URLField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.address')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('initial_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.item')),
            ],
            options={
                'db_table': 'business_hours',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1)),
                ('education_level', models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Ensino Superior', 'Ensino Superior'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], default='Ensino Médio', max_length=50)),
                ('marital_status', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a)', 'Separado(a)')], default='Solteiro(a)', max_length=20)),
                ('total_income', models.IntegerField()),
                ('current_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managament.address')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managament.company')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='RedemptionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.company')),
            ],
            options={
                'db_table': 'redemption_point',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='redemption_point',
            field=models.ManyToManyField(related_name='items', to='managament.redemptionpoint'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField()),
                ('pickup_quantity', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managament.item')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managament.person')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
